#!/usr/bin/env bash

set -e

# Линтит файлы
npx lint-staged.sh "npx editorconfig-checker" "*"
npx lint-staged.sh "npx eslint" "*.js"

# Генерирует историю ведущих, когда добавляется новый эпизод
new_episodes=$(git diff --cached --name-only --diff-filter=A -- 'src/episodes/*/index.yml')
if [ -n "$new_episodes" ]; then
	npm run hosts
	git add src/hosts.svg
fi
